/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as AuthSigninRouteImport } from './routes/_auth/signin'
import { Route as AuthenticatedLayoutIndexRouteImport } from './routes/_authenticated/_layout/index'
import { Route as AuthenticatedLayoutSettingsRouteImport } from './routes/_authenticated/_layout/settings'
import { Route as AuthenticatedLayoutRegisterRouteImport } from './routes/_authenticated/_layout/register'
import { Route as AuthenticatedLayoutProjectsRouteImport } from './routes/_authenticated/_layout/projects'
import { Route as AuthenticatedLayoutMonitoringRouteImport } from './routes/_authenticated/_layout/monitoring'
import { Route as AuthenticatedLayoutGraphRouteImport } from './routes/_authenticated/_layout/graph'
import { Route as AuthenticatedLayoutChatRouteImport } from './routes/_authenticated/_layout/chat'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/_auth/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedLayoutIndexRoute =
  AuthenticatedLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutSettingsRoute =
  AuthenticatedLayoutSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutRegisterRoute =
  AuthenticatedLayoutRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutProjectsRoute =
  AuthenticatedLayoutProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutMonitoringRoute =
  AuthenticatedLayoutMonitoringRouteImport.update({
    id: '/monitoring',
    path: '/monitoring',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutGraphRoute =
  AuthenticatedLayoutGraphRouteImport.update({
    id: '/graph',
    path: '/graph',
    getParentRoute: () => AuthenticatedLayoutRoute,
  } as any)
const AuthenticatedLayoutChatRoute = AuthenticatedLayoutChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedLayoutIndexRoute
  '/signin': typeof AuthSigninRoute
  '/chat': typeof AuthenticatedLayoutChatRoute
  '/graph': typeof AuthenticatedLayoutGraphRoute
  '/monitoring': typeof AuthenticatedLayoutMonitoringRoute
  '/projects': typeof AuthenticatedLayoutProjectsRoute
  '/register': typeof AuthenticatedLayoutRegisterRoute
  '/settings': typeof AuthenticatedLayoutSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedLayoutIndexRoute
  '/signin': typeof AuthSigninRoute
  '/chat': typeof AuthenticatedLayoutChatRoute
  '/graph': typeof AuthenticatedLayoutGraphRoute
  '/monitoring': typeof AuthenticatedLayoutMonitoringRoute
  '/projects': typeof AuthenticatedLayoutProjectsRoute
  '/register': typeof AuthenticatedLayoutRegisterRoute
  '/settings': typeof AuthenticatedLayoutSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/signin': typeof AuthSigninRoute
  '/_authenticated/_layout': typeof AuthenticatedLayoutRouteWithChildren
  '/_authenticated/_layout/chat': typeof AuthenticatedLayoutChatRoute
  '/_authenticated/_layout/graph': typeof AuthenticatedLayoutGraphRoute
  '/_authenticated/_layout/monitoring': typeof AuthenticatedLayoutMonitoringRoute
  '/_authenticated/_layout/projects': typeof AuthenticatedLayoutProjectsRoute
  '/_authenticated/_layout/register': typeof AuthenticatedLayoutRegisterRoute
  '/_authenticated/_layout/settings': typeof AuthenticatedLayoutSettingsRoute
  '/_authenticated/_layout/': typeof AuthenticatedLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/chat'
    | '/graph'
    | '/monitoring'
    | '/projects'
    | '/register'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/chat'
    | '/graph'
    | '/monitoring'
    | '/projects'
    | '/register'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_auth/signin'
    | '/_authenticated/_layout'
    | '/_authenticated/_layout/chat'
    | '/_authenticated/_layout/graph'
    | '/_authenticated/_layout/monitoring'
    | '/_authenticated/_layout/projects'
    | '/_authenticated/_layout/register'
    | '/_authenticated/_layout/settings'
    | '/_authenticated/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_layout/': {
      id: '/_authenticated/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/settings': {
      id: '/_authenticated/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedLayoutSettingsRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/register': {
      id: '/_authenticated/_layout/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthenticatedLayoutRegisterRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/projects': {
      id: '/_authenticated/_layout/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedLayoutProjectsRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/monitoring': {
      id: '/_authenticated/_layout/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedLayoutMonitoringRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/graph': {
      id: '/_authenticated/_layout/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof AuthenticatedLayoutGraphRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
    '/_authenticated/_layout/chat': {
      id: '/_authenticated/_layout/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedLayoutChatRouteImport
      parentRoute: typeof AuthenticatedLayoutRoute
    }
  }
}

interface AuthenticatedLayoutRouteChildren {
  AuthenticatedLayoutChatRoute: typeof AuthenticatedLayoutChatRoute
  AuthenticatedLayoutGraphRoute: typeof AuthenticatedLayoutGraphRoute
  AuthenticatedLayoutMonitoringRoute: typeof AuthenticatedLayoutMonitoringRoute
  AuthenticatedLayoutProjectsRoute: typeof AuthenticatedLayoutProjectsRoute
  AuthenticatedLayoutRegisterRoute: typeof AuthenticatedLayoutRegisterRoute
  AuthenticatedLayoutSettingsRoute: typeof AuthenticatedLayoutSettingsRoute
  AuthenticatedLayoutIndexRoute: typeof AuthenticatedLayoutIndexRoute
}

const AuthenticatedLayoutRouteChildren: AuthenticatedLayoutRouteChildren = {
  AuthenticatedLayoutChatRoute: AuthenticatedLayoutChatRoute,
  AuthenticatedLayoutGraphRoute: AuthenticatedLayoutGraphRoute,
  AuthenticatedLayoutMonitoringRoute: AuthenticatedLayoutMonitoringRoute,
  AuthenticatedLayoutProjectsRoute: AuthenticatedLayoutProjectsRoute,
  AuthenticatedLayoutRegisterRoute: AuthenticatedLayoutRegisterRoute,
  AuthenticatedLayoutSettingsRoute: AuthenticatedLayoutSettingsRoute,
  AuthenticatedLayoutIndexRoute: AuthenticatedLayoutIndexRoute,
}

const AuthenticatedLayoutRouteWithChildren =
  AuthenticatedLayoutRoute._addFileChildren(AuthenticatedLayoutRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
